services:
  discord:
    build: .
    image: boneless-couch
    volumes:
      - ./.env:/app/.env:ro
    command: python -m couchd.platforms.discord.main
    restart: unless-stopped

  twitch:
    image: boneless-couch
    volumes:
      - ./.env:/app/.env:ro
    command: python -m couchd.platforms.twitch.main
    ports:
      - "4343:4343"
    restart: unless-stopped
